openapi: 3.0.3
info:
  description: 'Congress.gov shares its application programming interface (API) with the public to ingest the Congressional data. <a href="sign-up/" target="_blank">Sign up for an API key</a> from api.data.gov that you can use to access web services provided by Congress.gov. To learn more, view our <a href="https://github.com/LibraryOfCongress/api.congress.gov/" target="_blank">GitHub repository</a>.

    '
  title: Congress.gov amendments congressional-record API
  version: '3'
servers:
- url: /v3
security:
- ApiKeyAuth: []
tags:
- name: congressional-record
  description: Returns Congressional Record data from the API
paths:
  /congressional-record:
    get:
      tags:
      - congressional-record
      summary: Returns a list of congressional record issues sorted by most recent.
      description: Returns a list of congressional record issues sorted by most recent.
      parameters:
      - $ref: '#/components/parameters/format'
      - $ref: '#/components/parameters/offset'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/y'
      - $ref: '#/components/parameters/m'
      - $ref: '#/components/parameters/d'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CongressionalRecord'
            application/xml:
              schema:
                $ref: '#/components/schemas/CongressionalRecord'
        '400':
          description: Invalid status value
components:
  parameters:
    d:
      name: d
      in: query
      description: The day the issue was published. For example, the value can be 28.
      required: false
      schema:
        type: integer
    offset:
      name: offset
      in: query
      description: The starting record returned. 0 is the first record.
      required: false
      schema:
        type: integer
    format:
      name: format
      in: query
      description: The data format. Value can be xml or json.
      required: false
      schema:
        type: string
        default: xml
        enum:
        - xml
        - json
    m:
      name: m
      in: query
      description: The month the issue was published. For example, the value can be 6.
      required: false
      schema:
        type: integer
    y:
      name: y
      in: query
      description: The year the issue was published. For example, the value can be 2022.
      required: false
      schema:
        type: integer
    limit:
      name: limit
      in: query
      description: The number of records returned. The maximum limit is 250.
      required: false
      schema:
        type: integer
  schemas:
    issues:
      type: object
      properties:
        Congress:
          type: string
          example: '117'
        Id:
          type: integer
          example: 26958
        Issue:
          type: string
          example: '109'
        Links:
          type: object
          properties:
            Digest:
              type: object
              properties:
                Label:
                  type: string
                  example: Daily Digest
                Ordinal:
                  type: integer
                  example: 1
                PDF:
                  type: array
                  items:
                    type: object
                    properties:
                      Part:
                        type: string
                        example: '1'
                      Url:
                        type: string
                        format: url
                        example: https://www.congress.gov/117/crec/2022/06/28/168/109/CREC-2022-06-28-dailydigest.pdf
            FullRecord:
              type: object
              properties:
                Label:
                  type: string
                  example: Entire Issue
                Ordinal:
                  type: integer
                  example: 5
                PDF:
                  type: array
                  items:
                    type: object
                    properties:
                      Part:
                        type: string
                        example: '1'
                      Url:
                        type: string
                        format: url
                        example: https://www.congress.gov/117/crec/2022/06/28/168/109/CREC-2022-06-28.pdf
            House:
              type: object
              properties:
                Label:
                  type: string
                  example: House Section
                Ordinal:
                  type: integer
                  example: 3
                PDF:
                  type: array
                  items:
                    type: object
                    properties:
                      Part:
                        type: string
                        example: '1'
                      Url:
                        type: string
                        format: url
                        example: https://www.congress.gov/117/crec/2022/06/28/168/109/CREC-2022-06-28-house.pdf
            Remarks:
              type: object
              properties:
                Label:
                  type: string
                  example: Extensions of Remarks Section
                Ordinal:
                  type: integer
                  example: 4
                PDF:
                  type: array
                  items:
                    type: object
                    properties:
                      Part:
                        type: string
                        example: '1'
                      Url:
                        type: string
                        format: url
                        example: https://www.congress.gov/117/crec/2022/06/28/168/109/CREC-2022-06-28-extensions.pdf
            Senate:
              type: object
              properties:
                Label:
                  type: string
                  example: Senate Section
                Ordinal:
                  type: integer
                  example: 2
                PDF:
                  type: array
                  items:
                    type: object
                    properties:
                      Part:
                        type: string
                        example: '1'
                      Url:
                        type: string
                        format: url
                        example: https://www.congress.gov/117/crec/2022/06/28/168/109/CREC-2022-06-28-senate.pdf
        PublishDate:
          type: string
          format: date
          example: '2022-02-18'
        Session:
          type: string
          example: '2'
        Volume:
          type: string
          example: '168'
    CongressionalRecord:
      type: object
      properties:
        IndexStart:
          type: integer
          example: 1
        Issues:
          type: array
          items:
            $ref: '#/components/schemas/issues'
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: query
      name: api_key
