openapi: 3.0.3
info:
  description: 'Congress.gov shares its application programming interface (API) with the public to ingest the Congressional data. <a href="sign-up/" target="_blank">Sign up for an API key</a> from api.data.gov that you can use to access web services provided by Congress.gov. To learn more, view our <a href="https://github.com/LibraryOfCongress/api.congress.gov/" target="_blank">GitHub repository</a>.

    '
  title: Congress.gov amendments summaries API
  version: '3'
servers:
- url: /v3
security:
- ApiKeyAuth: []
tags:
- name: summaries
  description: Returns summaries data from the API
paths:
  /summaries:
    get:
      tags:
      - summaries
      summary: Returns a list of summaries sorted by date of last update.
      description: Returns a list of summaries sorted by date of last update.
      parameters:
      - $ref: '#/components/parameters/format'
      - $ref: '#/components/parameters/offset'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/fromDateTime'
      - $ref: '#/components/parameters/toDateTime'
      - $ref: '#/components/parameters/sort'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Summaries'
            application/xml:
              schema:
                $ref: '#/components/schemas/Summaries'
        '400':
          description: Invalid status value
  /summaries/{congress}:
    get:
      tags:
      - summaries
      summary: Returns a list of summaries filtered by congress, sorted by date of last update.
      description: Returns a list of summaries filtered by congress, sorted by date of last update.
      parameters:
      - $ref: '#/components/parameters/congress'
      - $ref: '#/components/parameters/format'
      - $ref: '#/components/parameters/offset'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/fromDateTime'
      - $ref: '#/components/parameters/toDateTime'
      - $ref: '#/components/parameters/sort'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Summaries'
            application/xml:
              schema:
                $ref: '#/components/schemas/Summaries'
        '400':
          description: Invalid status value
  /summaries/{congress}/{billType}:
    get:
      tags:
      - summaries
      summary: Returns a list of summaries filtered by congress and by bill type, sorted by date of last update.
      description: Returns a list of summaries filtered by congress and by bill type, sorted by date of last update.
      parameters:
      - $ref: '#/components/parameters/congress'
      - $ref: '#/components/parameters/billType'
      - $ref: '#/components/parameters/format'
      - $ref: '#/components/parameters/offset'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/fromDateTime'
      - $ref: '#/components/parameters/toDateTime'
      - $ref: '#/components/parameters/sort'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Summaries'
            application/xml:
              schema:
                $ref: '#/components/schemas/Summaries'
        '400':
          description: Invalid status value
components:
  parameters:
    offset:
      name: offset
      in: query
      description: The starting record returned. 0 is the first record.
      required: false
      schema:
        type: integer
    format:
      name: format
      in: query
      description: The data format. Value can be xml or json.
      required: false
      schema:
        type: string
        default: xml
        enum:
        - xml
        - json
    billType:
      name: billType
      in: path
      description: The type of bill. Value can be hr, s, hjres, sjres, hconres, sconres, hres, or sres.
      required: true
      schema:
        type: string
    fromDateTime:
      name: fromDateTime
      in: query
      description: 'The starting timestamp to filter by update date. Use format: YYYY-MM-DDT00:00:00Z.'
      required: false
      schema:
        type: string
    toDateTime:
      name: toDateTime
      in: query
      description: 'The ending timestamp to filter by update date. Use format: YYYY-MM-DDT00:00:00Z.'
      required: false
      schema:
        type: string
    congress:
      name: congress
      in: path
      description: The congress number. For example, can be 117.
      required: true
      schema:
        type: integer
        format: int32
    sort:
      name: sort
      in: query
      description: Sort by update date in Congress.gov. Value can be updateDate+asc or updateDate+desc.
      required: false
      schema:
        type: string
    limit:
      name: limit
      in: query
      description: The number of records returned. The maximum limit is 250.
      required: false
      schema:
        type: integer
  schemas:
    summaryBill:
      type: object
      properties:
        congress:
          type: integer
          example: 117
        number:
          type: string
          example: 1234
        originChamber:
          type: string
          example: Senate
        originChamberCode:
          type: string
          example: S
        title:
          type: string
          example: Pay Our Capitol Police Act
        type:
          type: string
          example: HR
        updateDateIncludingText:
          type: string
          format: date
          example: '2021-08-08'
        url:
          type: string
          format: url
          example: https://api.congress.gov/v3/bill/117/hr/1234?format=json
    Summaries:
      type: array
      items:
        $ref: '#/components/schemas/summariesArray'
    summariesArray:
      type: object
      properties:
        actionDate:
          type: string
          format: date
          example: '2022-02-18T16:38:41Z'
        actionDesc:
          type: string
          example: Passed Senate
        bill:
          $ref: '#/components/schemas/summaryBill'
        currentChamber:
          type: string
          example: Senate
        currentChamberCode:
          type: string
          example: S
        lastSummaryUpdateDate:
          type: string
          format: date-time
          example: '2022-02-18T16:38:41Z'
        text:
          type: string
          example: <p><strong>COVID-19 Medical Production Act</strong></p> <p>This bill provides additional funding for FY2021 to acquire medical supplies, vaccines, and other equipment to combat COVID-19 (i.e., coronavirus disease 2019) using authorities under the Defense Production Act of 1950. That act confers on the President a broad set of authorities to influence domestic industry to provide essential materials and goods for the national defense.</p> <p>This funding is available through FY2025. Beginning in FY2023, it may be used to meet public health needs to address any pathogen determined by the President to have the potential to create a public health emergency.</p>
        updateDate:
          type: string
          format: date
          example: '2022-02-18T16:38:41Z'
        versionCode:
          type: string
          example: '173'
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: query
      name: api_key
