openapi: 3.0.3
info:
  description: 'Congress.gov shares its application programming interface (API) with the public to ingest the Congressional data. <a href="sign-up/" target="_blank">Sign up for an API key</a> from api.data.gov that you can use to access web services provided by Congress.gov. To learn more, view our <a href="https://github.com/LibraryOfCongress/api.congress.gov/" target="_blank">GitHub repository</a>.

    '
  title: Congress.gov amendments house-requirement API
  version: '3'
servers:
- url: /v3
security:
- ApiKeyAuth: []
tags:
- name: house-requirement
  description: Returns House requirement data from the API
paths:
  /house-requirement:
    get:
      tags:
      - house-requirement
      summary: Returns a list of House requirements.
      description: Returns a list of House requirements.
      parameters:
      - $ref: '#/components/parameters/format'
      - $ref: '#/components/parameters/offset'
      - $ref: '#/components/parameters/limit'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HouseRequirements'
            application/xml:
              schema:
                $ref: '#/components/schemas/HouseRequirements'
        '400':
          description: Invalid status value
  /house-requirement/{requirementNumber}:
    get:
      tags:
      - house-requirement
      summary: Returns detailed information for a specified House requirement.
      description: Returns detailed information for a specified House requirement.
      parameters:
      - $ref: '#/components/parameters/requirementNumber'
      - $ref: '#/components/parameters/format'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HouseRequirement'
            application/xml:
              schema:
                $ref: '#/components/schemas/HouseRequirement'
        '400':
          description: Invalid status value
  /house-requirement/{requirementNumber}/matching-communications:
    get:
      tags:
      - house-requirement
      summary: Returns a list of matching communications to a House requirement.
      description: Returns a list of matching communications to a House requirement.
      parameters:
      - $ref: '#/components/parameters/requirementNumber'
      - $ref: '#/components/parameters/format'
      - $ref: '#/components/parameters/offset'
      - $ref: '#/components/parameters/limit'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchCommunications'
            application/xml:
              schema:
                $ref: '#/components/schemas/MatchCommunications'
        '400':
          description: Invalid status value
components:
  parameters:
    offset:
      name: offset
      in: query
      description: The starting record returned. 0 is the first record.
      required: false
      schema:
        type: integer
    format:
      name: format
      in: query
      description: The data format. Value can be xml or json.
      required: false
      schema:
        type: string
        default: xml
        enum:
        - xml
        - json
    requirementNumber:
      name: requirementNumber
      in: path
      description: The requirement’s assigned number. For example, the value can be 8070.
      required: true
      schema:
        type: integer
    limit:
      name: limit
      in: query
      description: The number of records returned. The maximum limit is 250.
      required: false
      schema:
        type: integer
  schemas:
    HouseRequirements:
      type: object
      properties:
        houseRequirements:
          type: array
          items:
            $ref: '#/components/schemas/houseRequirement'
    HouseRequirement:
      type: object
      properties:
        houseRequirement:
          type: object
          properties:
            activeRecord:
              type: boolean
              example: true
            frequency:
              type: string
              example: '[No deadline specified].'
            legalAuthority:
              type: string
              example: 5 U.S.C. 801(a)(1)(A); Public Law 104–121, section 251; (110 Stat. 868)
            matchingCommunications:
              $ref: '#/components/schemas/matchCommunication'
            nature:
              type: string
              example: Congressional review of agency rulemaking.
            number:
              type: integer
              example: 8070
            parentAgency:
              type: string
              example: Multiple Executive Agencies and Departments
            submittingAgency:
              type: string
              example: Multiple Executive Agencies and Departments
            updateDate:
              type: string
              format: date
              example: '2021-08-13'
    communicationType:
      type: object
      properties:
        code:
          type: string
          example: EC
        name:
          type: string
          example: Executive Communication
    MatchCommunications:
      type: object
      properties:
        matchCommunications:
          type: array
          items:
            $ref: '#/components/schemas/matchCommunications'
    matchCommunications:
      type: object
      properties:
        chamber:
          type: string
          example: House
        communicationType:
          $ref: '#/components/schemas/communicationType'
        congress:
          type: integer
          example: 112
        number:
          type: integer
          example: 2
        url:
          type: string
          format: url
          example: https://api.congress.gov/v3/house-communication/112/EC/2?format=json
    houseRequirement:
      type: object
      properties:
        number:
          type: integer
          example: 8070
        updateDate:
          type: string
          format: date
          example: '2021-08-13'
        url:
          type: string
          format: url
          example: https://api.congress.gov/v3/house-requirement/8070?format=json
    matchCommunication:
      type: object
      properties:
        count:
          type: integer
          example: 90774
        url:
          type: string
          format: url
          example: https://api.congress.gov/v3/house-requirement/8070/matching-communications?format=json
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: query
      name: api_key
